/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppPage: typeof import('./../src/components/AppPage.vue')['default']
    Container: typeof import('@/components/AppPage.vue')['default']
    ElSvgIcon: typeof import('./../src/components/ElSvgIcon.vue')['default']
    IconSelector: typeof import('./../src/components/IconSelector.vue')['default']
    MenuIcon: typeof import('./../src/components/MenuIcon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./../src/icons/SvgIcon.vue')['default']
    TestUnit: typeof import('./../src/components/TestUnit.vue')['default']
  }
}
